name: Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  programs:
    runs-on: ubuntu-latest
    name: Build and publish the SDK
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2.2.0
        with:
          node-version: 14.x
          registry-url: "https://registry.npmjs.org"
      - name: Cache Node modules
        uses: actions/cache@v2
        id: cache-node-modules
        with:
          path: ./node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
      - name: Install Yarn dependencies
        run: yarn install
      - run: echo '//registry.npmjs.org/:_authToken=${NODE_AUTH_TOKEN}' > .npmrc
      - name: Publish
        run: yarn lerna publish --yes from-package
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
